In [ ]:
#모듈 불러오기 1

In [1]:
import module_test

In [3]:
module_test.number_sum(1,3)

4

In [4]:
#모듈 불러오기 2

In [6]:
from module_test import number_sum

In [7]:
number_sum(1,2)

3

1. 1차원 array 만들기 방법 1

In [8]:
#numpy 모듈을 np라고 하겠다
import numpy as np

In [10]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [11]:
print(type(list1))

<class 'list'>


In [14]:
#만들어진 리스트를 배열의 형태로 저장
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [15]:
print(type(arr))

<class 'numpy.ndarray'>


1차원 array 만들기 방법 2

In [16]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [17]:
print(type(arr1))

<class 'numpy.ndarray'>


2. 2차원 array 만들기

In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

3. 배열의 크기(행과 열) 확인하기 -> .shape

In [31]:
arr1.shape

(5,)

In [32]:
arr2.shape

(2, 3)

4. 배열의 전체요소 확인하기 ->.size

In [33]:
arr1.size

5

In [34]:
arr2.size

6

5. 배열의 데이터 타입 확인하기 -> .dtype

In [35]:
arr1.dtype

dtype('int32')

In [36]:
arr2.dtype

dtype('int32')

In [37]:
arr3 = np.array([1,2,2.3])

In [39]:
arr3.dtype

dtype('float64')

6. .ndim

In [40]:
arr1.ndim

1

In [41]:
arr2.ndim

2

7. 특정한 값으로 배열 생성하기 = .zeros

In [43]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr_zeros.dtype #0.xx 으로 나오는데 int형으로 만들고싶다면 ,dtype = 'i'

dtype('float64')

In [45]:
arr_zeros = np.zeros((3,4), dtype ='i') 
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [47]:
arr_ones = np.ones((5,5), dtype = 'i')
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

8. 특정한 값으로 배열 생성하기

In [48]:
arr_full = np.full((5,6), 7) #full 함수는 기본적으로 int형
arr_full

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [49]:
arr_full = np.full((2,3),3)
arr_full

array([[3, 3, 3],
       [3, 3, 3]])

In [54]:
# 1~50이 담긴 리스트 만들기
list1 = []
# for문 사용하여 1~50까지 list1에 담아주기
# .append()
# print() 출력 확인하기
for i in range(1, 50+1):
    list1.append(i)
    
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [57]:
# list1 1차원 배열의 형태로 만들어 주기
list_arr = np.array(list1)
list_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [58]:
list2_arr = np.arange(1, 51)
list2_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [60]:
# 1~50까지 10씩 증가하는 배열 만들기
list3_arr = np.arange(1, 51, 10)
list3_arr

array([ 1, 11, 21, 31, 41])

9. 랜덤 값 배열 생성하기

In [61]:
import random

In [67]:
#numpy에서 랜덤수 생성 공식이라 그대로 외우기
rd_arr = np.random.rand(2,3) #0~1사이의 랜덤값 생성 rand(행과 열)
rd_arr

array([[0.37807936, 0.37856561, 0.15252371],
       [0.68194519, 0.56142241, 0.62155954]])

In [66]:
rd_arr = np.random.randint(2,10) #2~10사이의 랜덤값 생성 randint(랜덤수의 범위)
rd_arr 

8

In [68]:
#2~10사이의 랜덤값 생성, 2행 3열로 randint(랜덤수의 범위)
rd_arr = np.random.randint(2,10, size=(2,3))
rd_arr 

array([[6, 4, 9],
       [2, 4, 2]])

In [70]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(a+b)
print(a-b)
print(a%b)
print(a*b)

[ 2  4  6  8 10]
[0 0 0 0 0]
[0 0 0 0 0]
[ 1  4  9 16 25]


In [72]:
arr = np.array([[1,2,3,],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
# 1행 인덱싱 해오기
print(arr[0])

[1 2 3]


In [75]:
print(arr[0][0])

1


In [76]:
print(arr[0,0])

1


In [77]:
print(arr[1,2])

6


In [79]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
print(arr[3:8])

[3 4 5 6 7]


In [86]:
arr[3:8] = 12
arr

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [92]:
#. reshape() -> 원하는 모양으로 행과 열을 지정하기
arr2 = np.arange(1, 51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [101]:
# arr2[행(시작:끝),열(시작:끝)]
arr2[:2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [112]:
arr2[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [113]:
arr2[:,0]

array([ 1, 11, 21, 31, 41])

In [117]:
arr2[:4,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [120]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [123]:
arr2[2:4,2] #슬라이싱 행[시작:끝,열 시작:끝]

array([23, 33])

In [126]:
arr2[[2,3],[2,3]] 

#[[행시작:행끝,열시작:열끝]]
#[[행1, 행2],[열1 ,열2]]

array([23, 34])

In [127]:
name = np.array(["대진", "성일", "충기", "창섭"])
name

array(['대진', '성일', '충기', '창섭'], dtype='<U2')

In [131]:
bol = np.array([False, True, True, False])
bol

array([False,  True,  True, False])

In [132]:
name[bol] #트루값만 반환

array(['성일', '충기'], dtype='<U2')

In [135]:
score = np.array([[60,60],[70,70],[80,80],[90,90]])
score

array([[60, 60],
       [70, 70],
       [80, 80],
       [90, 90]])

In [136]:
score[name=="대진"]

array([[60, 60]])

In [137]:
arr = np.random.randint(1,10, size=(2,5))
arr

array([[3, 6, 5, 1, 8],
       [6, 8, 3, 7, 6]])

In [143]:
# sum() -> 모든 요소를 다 더해주는 함수
print(arr.sum())
print(np.sum(arr))

53
53


In [146]:
#mean() -> 평균을 구하는 함수
print(arr.mean())
print(np.mean(arr))

5.3
5.3


In [147]:
# abs() -> 절대값 구하는 함수
arr = np.array([-1,-2,-3,-4])
arr

array([-1, -2, -3, -4])

In [152]:
np.abs(arr)

array([1, 2, 3, 4])